### ISSUE TITLE
Changed names in teerank

### ISSUE THREAD

**Issue by nzyuzin** [needs/teerank#10]
Hi,

Recently I have discovered that the names of several players (including me and zandyZ) have been changed, while retaining all the other attributes, like score and clan.
http://teerank.com/pages/1.html
zandyZ's rank record got renamed to 'zanchho' and mine to 'Shiister'.

How could this happen? :O

**Comment by needs** [comment]
I have absolutely no ideas ^^!

Well, I host teeworlds on a pretty cheap server, a 10 Gb SSD from OVH.  While it does it's job pretty good, I think at some point the SSD was full.  And when I upgraded teerank to the next version I got tons of errors, some files could not be created, some write failed, etc...

At that point I noticed that elo points of some players were reset to 1500. So it's very likely the right explanation.

Do you want me to fix your record by hand?

**Comment by nzyuzin** [comment]
zandyZ may want it, I prefer to crawl back from the start. :)

I was just surprised by the event, especially considering that it was only 2 players.

**Comment by needs** [comment]
In fact some other players were reset as well (I got reset too).  I think every players who recently played are affected by the bug.  I will rename "zanchho" to "zandyZ".

I will also leave this issue open so you can post other rename requests as well :)

**Comment by nzyuzin** [comment]
Still renaming seems pretty strange. Is malicious intent possible?

**Comment by needs** [comment]
I hope not, but I have to admit that I don't feel very confident about my checks on user inputs.  I'm going to review the code and find a way to do reliable backups and put them on another machine.

**Comment by nzyuzin** [comment]
Another renaming spotted: "Teegirl" => "Teefrozen?".

That looks like a disturbing trend now. No idea what causes it though.

Update: Same happened to "SpaceTime Zushi". His name changed into "SpaceShyGuy*".
Update: "jake" => "jakTheHalfTee"

At this point, I think, the possibility of upgrade errors is out of question.

**Comment by nzyuzin** [comment]
The issue was indeed due to the failed migration.
