### ISSUE TITLE
Incorrect display of unicode symbols

### ISSUE THREAD

**Issue by nzyuzin** [needs/teerank#2]
As seen on screenshot below, unicode characters are not displayed correctly.
For example: Magnet should have ÆON clan and R4z0r should have χron clan.
![teerank-unicode](https://cloud.githubusercontent.com/assets/4072673/12764988/d77f8804-ca15-11e5-9098-d14a5c876bb6.jpg)

**Comment by needs** [comment]
I actually fixed the issue in commit 6b88c4d8c5b0c250caad56d0bafd45cf5b659234, but forgot to upload the latest version to teerank.com.  I just updated it and utf-8 string should be properly handled and start to spread.  Thank for the report!

**Comment by nzyuzin** [comment]
Oh, the issue is solved then. Thanks!
