### ISSUE TITLE
Favorite maps

### ISSUE THREAD

**Issue by nzyuzin** [needs/teerank#3]
> A more easy-to-code idea is to just record the favorite map of the player and display it in the ranking.  So a player getting a high rank by playing mostly ctf2 is more likely to be a pro than ones playing ctf5.  What's your thoughts about the issue?
> Favorite map is indeed an interesting idea, an option to filter on it could be implemented then to separate ctf2 players from ctf5 players.

**Comment by needs** [comment]
7 years after this issue was opened, ranks are tracked by map and playtimes are computed for each maps and game types, favorite maps will be at the top of the maps list!
