### ISSUE TITLE
Obsolete rank is shown on clan page

### ISSUE THREAD

**Issue by nzyuzin** [needs/teerank#9]
If you browse first page then you can see Shiki 3rd.
http://teerank.com/pages/1.html
If you browse his clan page you can see him 15th with wrong (old) score.
http://teerank.com/clans/566f67656c73616e6700.html
Edit: I suppose using a relational database would prevent occurrence of such issues.

**Comment by needs** [comment]
Actually this is more a caching issue.  For some reasons the clan page is not regenerated, despite the fact that it should be regenerated because the database is more recent than the cached file.  I've some ongoing work that will fix it.

**Comment by needs** [comment]
Commit 71a8707b8047d92a1442e81e9d331cae33f4a384 fixed it.  I updated teerank.com and clans pages should now be up-to-date!

**Comment by nzyuzin** [comment]
Thanks for this!

Only later have I realised that the problem is more likely to be due to caching...
